[project]
authors = ["@jasmcaus", "@xburralabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "base_position_manager"

[dependencies]
helpers = { path = "../../helpers" }
core_interfaces = { path = "../interfaces" }
fungible_abi = { git = "https://github.com/burralabs/fuel-asset-standard" }