[project]
authors = ["@jasmcaus", "@xburralabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "timelock"

[dependencies]
helpers = { path = "../../helpers" }
interfaces = { path = "../../interfaces" }
core_interfaces = { path = "../../core/interfaces" }
referrals_interfaces = { path = "../../referrals/interfaces" }
asset_interfaces = { path = "../../assets/interfaces" }
peripheral_interfaces = { path = "../interfaces" }
