[project]
authors = ["@jasmcaus", "@xburralabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "referral_storage"

[dependencies]
helpers = { path = "../../helpers" }
referrals_interfaces = { path = "../interfaces" }
