[project]
authors = ["@jasmcaus", "@xburralabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "pyth-vault-pricefeed"

[dependencies]
helpers = { path = "../../helpers" }
core_interfaces = { path = "../interfaces" }
interfaces = { path = "../../interfaces" }
pyth_interface = { path = "../../pyth/pyth-interface" }