[project]
authors = ["@jasmcaus", "@xburralabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "utils"

[dependencies]
helpers = { path = "../helpers" }
core_interfaces = { path = "../core/interfaces" }