[project]
authors = ["@jasmcaus", "@xburralabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "old_vault"

[dependencies]
helpers = { path = "../../helpers" }
core_interfaces = { path = "../interfaces" }
asset_interfaces = { path = "../../assets/interfaces" }
interfaces = { path = "../../interfaces" }