[project]
authors = ["@jasmcaus", "@xburralabs"]
entry = "main.sw"
license = "Apache 2.0"
name = "glp"

[dependencies]
asset_interfaces = { path = "../interfaces" }
helpers = { path = "../../helpers" }