[project]
authors = ["@jasmcaus", "@xburralabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "position_manager"

[dependencies]
helpers = { path = "../../helpers" }
core_interfaces = { path = "../interfaces" }
